package org.srvvp.knowledgetree.entity;
// Generated 5 Apr, 2017 12:15:43 PM by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Address generated by hbm2java
 */
@Entity
@Table(name = "address", catalog = "knowledgetree")
public class Address implements java.io.Serializable {

	private String id;
	private City city;
	private District district;
	private Person person;
	private String value;
	private String houseNumber;
	private String street;
	private String area;

	public Address() {
	}

	public Address(String id) {
		this.id = id;
	}
	public Address(String id, City city, District district, Person person,
			String value, String houseNumber, String street, String area) {
		this.id = id;
		this.city = city;
		this.district = district;
		this.person = person;
		this.value = value;
		this.houseNumber = houseNumber;
		this.street = street;
		this.area = area;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, length = 20)
	@NotNull
	@Length(max = 20)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "City_id", referencedColumnName = "id"),
			@JoinColumn(name = "City_State_id", referencedColumnName = "State_id"),
			@JoinColumn(name = "City_Country_id", referencedColumnName = "Country_id")})
	public City getCity() {
		return this.city;
	}

	public void setCity(City city) {
		this.city = city;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "District_id", referencedColumnName = "id"),
			@JoinColumn(name = "District_State_id", referencedColumnName = "State_id"),
			@JoinColumn(name = "District_Country_id", referencedColumnName = "Country_id")})
	public District getDistrict() {
		return this.district;
	}

	public void setDistrict(District district) {
		this.district = district;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Person")
	public Person getPerson() {
		return this.person;
	}

	public void setPerson(Person person) {
		this.person = person;
	}

	@Column(name = "Value", length = 500)
	@Length(max = 500)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@Column(name = "HouseNumber", length = 30)
	@Length(max = 30)
	public String getHouseNumber() {
		return this.houseNumber;
	}

	public void setHouseNumber(String houseNumber) {
		this.houseNumber = houseNumber;
	}

	@Column(name = "Street", length = 30)
	@Length(max = 30)
	public String getStreet() {
		return this.street;
	}

	public void setStreet(String street) {
		this.street = street;
	}

	@Column(name = "Area", length = 30)
	@Length(max = 30)
	public String getArea() {
		return this.area;
	}

	public void setArea(String area) {
		this.area = area;
	}

}
