package org.srvvp.knowledgetree.entity;
// Generated 5 Apr, 2017 12:15:43 PM by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * CityId generated by hbm2java
 */
@Embeddable
public class CityId implements java.io.Serializable {

	private String id;
	private String stateId;
	private String countryId;

	public CityId() {
	}

	public CityId(String id, String stateId, String countryId) {
		this.id = id;
		this.stateId = stateId;
		this.countryId = countryId;
	}

	@Column(name = "id", nullable = false, length = 10)
	@NotNull
	@Length(max = 10)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "State_id", nullable = false, length = 10)
	@NotNull
	@Length(max = 10)
	public String getStateId() {
		return this.stateId;
	}

	public void setStateId(String stateId) {
		this.stateId = stateId;
	}

	@Column(name = "Country_id", nullable = false, length = 10)
	@NotNull
	@Length(max = 10)
	public String getCountryId() {
		return this.countryId;
	}

	public void setCountryId(String countryId) {
		this.countryId = countryId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CityId))
			return false;
		CityId castOther = (CityId) other;

		return ((this.getId() == castOther.getId()) || (this.getId() != null
				&& castOther.getId() != null && this.getId().equals(
				castOther.getId())))
				&& ((this.getStateId() == castOther.getStateId()) || (this
						.getStateId() != null
						&& castOther.getStateId() != null && this.getStateId()
						.equals(castOther.getStateId())))
				&& ((this.getCountryId() == castOther.getCountryId()) || (this
						.getCountryId() != null
						&& castOther.getCountryId() != null && this
						.getCountryId().equals(castOther.getCountryId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result
				+ (getStateId() == null ? 0 : this.getStateId().hashCode());
		result = 37 * result
				+ (getCountryId() == null ? 0 : this.getCountryId().hashCode());
		return result;
	}

}
