package org.srvvp.knowledgetree.entity;
// Generated 5 Apr, 2017 12:15:43 PM by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Language generated by hbm2java
 */
@Entity
@Table(name = "language", catalog = "knowledgetree")
public class Language implements java.io.Serializable {

	private String id;
	private String name;
	private Integer unicodeBlock;
	private Set<WorkInLanguage> workInLanguages = new HashSet<WorkInLanguage>(0);

	public Language() {
	}

	public Language(String id) {
		this.id = id;
	}
	public Language(String id, String name, Integer unicodeBlock,
			Set<WorkInLanguage> workInLanguages) {
		this.id = id;
		this.name = name;
		this.unicodeBlock = unicodeBlock;
		this.workInLanguages = workInLanguages;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, length = 20)
	@NotNull
	@Length(max = 20)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "Name", length = 100)
	@Length(max = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "UnicodeBlock")
	public Integer getUnicodeBlock() {
		return this.unicodeBlock;
	}

	public void setUnicodeBlock(Integer unicodeBlock) {
		this.unicodeBlock = unicodeBlock;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "language")
	public Set<WorkInLanguage> getWorkInLanguages() {
		return this.workInLanguages;
	}

	public void setWorkInLanguages(Set<WorkInLanguage> workInLanguages) {
		this.workInLanguages = workInLanguages;
	}

}
