package org.srvvp.knowledgetree.entity;
// Generated 5 Apr, 2017 12:15:43 PM by Hibernate Tools 3.2.4.GA

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.hibernate.validator.NotNull;

/**
 * PersonHasAffiliation generated by hbm2java
 */
@Entity
@Table(name = "person_has_affiliation", catalog = "knowledgetree")
public class PersonHasAffiliation implements java.io.Serializable {

	private PersonHasAffiliationId id;
	private Affiliation affiliation;
	private Person person;

	public PersonHasAffiliation() {
	}

	public PersonHasAffiliation(PersonHasAffiliationId id,
			Affiliation affiliation, Person person) {
		this.id = id;
		this.affiliation = affiliation;
		this.person = person;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "person", column = @Column(name = "person", nullable = false, length = 20)),
			@AttributeOverride(name = "affiliation", column = @Column(name = "affiliation", nullable = false, length = 20))})
	@NotNull
	public PersonHasAffiliationId getId() {
		return this.id;
	}

	public void setId(PersonHasAffiliationId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "affiliation", nullable = false, insertable = false, updatable = false)
	@NotNull
	public Affiliation getAffiliation() {
		return this.affiliation;
	}

	public void setAffiliation(Affiliation affiliation) {
		this.affiliation = affiliation;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "person", nullable = false, insertable = false, updatable = false)
	@NotNull
	public Person getPerson() {
		return this.person;
	}

	public void setPerson(Person person) {
		this.person = person;
	}

}
