package org.srvvp.knowledgetree.entity;
// Generated 5 Apr, 2017 12:15:43 PM by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * PersonHasRoleId generated by hbm2java
 */
@Embeddable
public class PersonHasRoleId implements java.io.Serializable {

	private String person;
	private String role;

	public PersonHasRoleId() {
	}

	public PersonHasRoleId(String person, String role) {
		this.person = person;
		this.role = role;
	}

	@Column(name = "person", nullable = false, length = 20)
	@NotNull
	@Length(max = 20)
	public String getPerson() {
		return this.person;
	}

	public void setPerson(String person) {
		this.person = person;
	}

	@Column(name = "role", nullable = false, length = 20)
	@NotNull
	@Length(max = 20)
	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PersonHasRoleId))
			return false;
		PersonHasRoleId castOther = (PersonHasRoleId) other;

		return ((this.getPerson() == castOther.getPerson()) || (this
				.getPerson() != null
				&& castOther.getPerson() != null && this.getPerson().equals(
				castOther.getPerson())))
				&& ((this.getRole() == castOther.getRole()) || (this.getRole() != null
						&& castOther.getRole() != null && this.getRole()
						.equals(castOther.getRole())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getPerson() == null ? 0 : this.getPerson().hashCode());
		result = 37 * result
				+ (getRole() == null ? 0 : this.getRole().hashCode());
		return result;
	}

}
