package org.srvvp.knowledgetree.entity;
// Generated 5 Apr, 2017 12:15:43 PM by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Role generated by hbm2java
 */
@Entity
@Table(name = "role", catalog = "knowledgetree")
public class Role implements java.io.Serializable {

	private String id;
	private String name;
	private Set<PersonHasRole> personHasRoles = new HashSet<PersonHasRole>(0);

	public Role() {
	}

	public Role(String id) {
		this.id = id;
	}
	public Role(String id, String name, Set<PersonHasRole> personHasRoles) {
		this.id = id;
		this.name = name;
		this.personHasRoles = personHasRoles;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, length = 20)
	@NotNull
	@Length(max = 20)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "Name", length = 30)
	@Length(max = 30)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "role")
	public Set<PersonHasRole> getPersonHasRoles() {
		return this.personHasRoles;
	}

	public void setPersonHasRoles(Set<PersonHasRole> personHasRoles) {
		this.personHasRoles = personHasRoles;
	}

}
