package org.srvvp.knowledgetree.entity;
// Generated 5 Apr, 2017 12:15:43 PM by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Subject generated by hbm2java
 */
@Entity
@Table(name = "subject", catalog = "knowledgetree")
public class Subject implements java.io.Serializable {

	private String id;
	private String name;
	private String description;
	private Set<SubjectHasWork> subjectHasWorks = new HashSet<SubjectHasWork>(0);
	private Set<SubjectHasTag> subjectHasTags = new HashSet<SubjectHasTag>(0);
	private Set<SubjectRelatestoSubject> subjectRelatestoSubjectsForSubject1 = new HashSet<SubjectRelatestoSubject>(
			0);
	private Set<SubjectRelatestoSubject> subjectRelatestoSubjectsForSubject2 = new HashSet<SubjectRelatestoSubject>(
			0);

	public Subject() {
	}

	public Subject(String id, String name) {
		this.id = id;
		this.name = name;
	}
	public Subject(String id, String name, String description,
			Set<SubjectHasWork> subjectHasWorks,
			Set<SubjectHasTag> subjectHasTags,
			Set<SubjectRelatestoSubject> subjectRelatestoSubjectsForSubject1,
			Set<SubjectRelatestoSubject> subjectRelatestoSubjectsForSubject2) {
		this.id = id;
		this.name = name;
		this.description = description;
		this.subjectHasWorks = subjectHasWorks;
		this.subjectHasTags = subjectHasTags;
		this.subjectRelatestoSubjectsForSubject1 = subjectRelatestoSubjectsForSubject1;
		this.subjectRelatestoSubjectsForSubject2 = subjectRelatestoSubjectsForSubject2;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, length = 20)
	@NotNull
	@Length(max = 20)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "Name", nullable = false, length = 30)
	@NotNull
	@Length(max = 30)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "Description", length = 5000)
	@Length(max = 5000)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "subject")
	public Set<SubjectHasWork> getSubjectHasWorks() {
		return this.subjectHasWorks;
	}

	public void setSubjectHasWorks(Set<SubjectHasWork> subjectHasWorks) {
		this.subjectHasWorks = subjectHasWorks;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "subject")
	public Set<SubjectHasTag> getSubjectHasTags() {
		return this.subjectHasTags;
	}

	public void setSubjectHasTags(Set<SubjectHasTag> subjectHasTags) {
		this.subjectHasTags = subjectHasTags;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "subjectBySubject1")
	public Set<SubjectRelatestoSubject> getSubjectRelatestoSubjectsForSubject1() {
		return this.subjectRelatestoSubjectsForSubject1;
	}

	public void setSubjectRelatestoSubjectsForSubject1(
			Set<SubjectRelatestoSubject> subjectRelatestoSubjectsForSubject1) {
		this.subjectRelatestoSubjectsForSubject1 = subjectRelatestoSubjectsForSubject1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "subjectBySubject2")
	public Set<SubjectRelatestoSubject> getSubjectRelatestoSubjectsForSubject2() {
		return this.subjectRelatestoSubjectsForSubject2;
	}

	public void setSubjectRelatestoSubjectsForSubject2(
			Set<SubjectRelatestoSubject> subjectRelatestoSubjectsForSubject2) {
		this.subjectRelatestoSubjectsForSubject2 = subjectRelatestoSubjectsForSubject2;
	}

}
