package org.srvvp.knowledgetree.entity;
// Generated 5 Apr, 2017 12:15:43 PM by Hibernate Tools 3.2.4.GA

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.hibernate.validator.NotNull;

/**
 * SubjectHasTag generated by hbm2java
 */
@Entity
@Table(name = "subject_has_tag", catalog = "knowledgetree")
public class SubjectHasTag implements java.io.Serializable {

	private SubjectHasTagId id;
	private Tagsubject tagsubject;
	private Subject subject;

	public SubjectHasTag() {
	}

	public SubjectHasTag(SubjectHasTagId id, Tagsubject tagsubject,
			Subject subject) {
		this.id = id;
		this.tagsubject = tagsubject;
		this.subject = subject;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "subject", column = @Column(name = "subject", nullable = false, length = 20)),
			@AttributeOverride(name = "tag", column = @Column(name = "tag", nullable = false))})
	@NotNull
	public SubjectHasTagId getId() {
		return this.id;
	}

	public void setId(SubjectHasTagId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tag", nullable = false, insertable = false, updatable = false)
	@NotNull
	public Tagsubject getTagsubject() {
		return this.tagsubject;
	}

	public void setTagsubject(Tagsubject tagsubject) {
		this.tagsubject = tagsubject;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "subject", nullable = false, insertable = false, updatable = false)
	@NotNull
	public Subject getSubject() {
		return this.subject;
	}

	public void setSubject(Subject subject) {
		this.subject = subject;
	}

}
