package org.srvvp.knowledgetree.entity;
// Generated 5 Apr, 2017 12:15:43 PM by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Tag generated by hbm2java
 */
@Entity
@Table(name = "tag", catalog = "knowledgetree")
public class Tag implements java.io.Serializable {

	private String id;
	private Tag tag;
	private String name;
	private Set<Tag> tags = new HashSet<Tag>(0);

	public Tag() {
	}

	public Tag(String id) {
		this.id = id;
	}
	public Tag(String id, Tag tag, String name, Set<Tag> tags) {
		this.id = id;
		this.tag = tag;
		this.name = name;
		this.tags = tags;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@NotNull
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "BelongsTo")
	public Tag getTag() {
		return this.tag;
	}

	public void setTag(Tag tag) {
		this.tag = tag;
	}

	@Column(name = "Name", length = 30)
	@Length(max = 30)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tag")
	public Set<Tag> getTags() {
		return this.tags;
	}

	public void setTags(Set<Tag> tags) {
		this.tags = tags;
	}

}
