package org.srvvp.knowledgetree.entity;
// Generated 5 Apr, 2017 12:15:43 PM by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Tagsubject generated by hbm2java
 */
@Entity
@Table(name = "tagsubject", catalog = "knowledgetree")
public class Tagsubject implements java.io.Serializable {

	private String id;
	private Tagsubject tagsubject;
	private String name;
	private Set<Tagsubject> tagsubjects = new HashSet<Tagsubject>(0);
	private Set<SubjectHasTag> subjectHasTags = new HashSet<SubjectHasTag>(0);

	public Tagsubject() {
	}

	public Tagsubject(String id) {
		this.id = id;
	}
	public Tagsubject(String id, Tagsubject tagsubject, String name,
			Set<Tagsubject> tagsubjects, Set<SubjectHasTag> subjectHasTags) {
		this.id = id;
		this.tagsubject = tagsubject;
		this.name = name;
		this.tagsubjects = tagsubjects;
		this.subjectHasTags = subjectHasTags;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@NotNull
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "BelongsTo")
	public Tagsubject getTagsubject() {
		return this.tagsubject;
	}

	public void setTagsubject(Tagsubject tagsubject) {
		this.tagsubject = tagsubject;
	}

	@Column(name = "Name", length = 30)
	@Length(max = 30)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tagsubject")
	public Set<Tagsubject> getTagsubjects() {
		return this.tagsubjects;
	}

	public void setTagsubjects(Set<Tagsubject> tagsubjects) {
		this.tagsubjects = tagsubjects;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tagsubject")
	public Set<SubjectHasTag> getSubjectHasTags() {
		return this.subjectHasTags;
	}

	public void setSubjectHasTags(Set<SubjectHasTag> subjectHasTags) {
		this.subjectHasTags = subjectHasTags;
	}

}
