package org.srvvp.knowledgetree.entity;
// Generated 5 Apr, 2017 12:15:43 PM by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Tagwork generated by hbm2java
 */
@Entity
@Table(name = "tagwork", catalog = "knowledgetree")
public class Tagwork implements java.io.Serializable {

	private String id;
	private Tagwork tagwork;
	private String name;
	private Set<Tagwork> tagworks = new HashSet<Tagwork>(0);
	private Set<WorkHasTag> workHasTags = new HashSet<WorkHasTag>(0);

	public Tagwork() {
	}

	public Tagwork(String id) {
		this.id = id;
	}
	public Tagwork(String id, Tagwork tagwork, String name,
			Set<Tagwork> tagworks, Set<WorkHasTag> workHasTags) {
		this.id = id;
		this.tagwork = tagwork;
		this.name = name;
		this.tagworks = tagworks;
		this.workHasTags = workHasTags;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@NotNull
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "BelongsTo")
	public Tagwork getTagwork() {
		return this.tagwork;
	}

	public void setTagwork(Tagwork tagwork) {
		this.tagwork = tagwork;
	}

	@Column(name = "Name", length = 30)
	@Length(max = 30)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tagwork")
	public Set<Tagwork> getTagworks() {
		return this.tagworks;
	}

	public void setTagworks(Set<Tagwork> tagworks) {
		this.tagworks = tagworks;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tagwork")
	public Set<WorkHasTag> getWorkHasTags() {
		return this.workHasTags;
	}

	public void setWorkHasTags(Set<WorkHasTag> workHasTags) {
		this.workHasTags = workHasTags;
	}

}
