package org.srvvp.knowledgetree.entity;
// Generated 5 Apr, 2017 12:15:43 PM by Hibernate Tools 3.2.4.GA

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import org.hibernate.validator.NotNull;

/**
 * ViewSubjectSubject generated by hbm2java
 */
@Entity
@Table(name = "view_subject_subject", catalog = "knowledgetree")
public class ViewSubjectSubject implements java.io.Serializable {

	private ViewSubjectSubjectId id;

	public ViewSubjectSubject() {
	}

	public ViewSubjectSubject(ViewSubjectSubjectId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "sub1id", column = @Column(name = "sub1Id", nullable = false, length = 20)),
			@AttributeOverride(name = "subject1", column = @Column(name = "subject1", nullable = false, length = 30)),
			@AttributeOverride(name = "subject1description", column = @Column(name = "subject1Description", length = 5000)),
			@AttributeOverride(name = "sub2id", column = @Column(name = "sub2Id", nullable = false, length = 20)),
			@AttributeOverride(name = "subject2", column = @Column(name = "subject2", nullable = false, length = 30)),
			@AttributeOverride(name = "subject2description", column = @Column(name = "subject2Description", length = 5000)),
			@AttributeOverride(name = "relation", column = @Column(name = "relation", length = 100)),
			@AttributeOverride(name = "relationDescription", column = @Column(name = "relation_description", length = 1000))})
	@NotNull
	public ViewSubjectSubjectId getId() {
		return this.id;
	}

	public void setId(ViewSubjectSubjectId id) {
		this.id = id;
	}

}
