package org.srvvp.knowledgetree.entity;
// Generated 5 Apr, 2017 12:15:43 PM by Hibernate Tools 3.2.4.GA

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import org.hibernate.validator.NotNull;

/**
 * ViewSubjectWork generated by hbm2java
 */
@Entity
@Table(name = "view_subject_work", catalog = "knowledgetree")
public class ViewSubjectWork implements java.io.Serializable {

	private ViewSubjectWorkId id;

	public ViewSubjectWork() {
	}

	public ViewSubjectWork(ViewSubjectWorkId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "subject", column = @Column(name = "Subject", nullable = false, length = 30)),
			@AttributeOverride(name = "work", column = @Column(name = "Work", length = 45)),
			@AttributeOverride(name = "relation", column = @Column(name = "Relation", length = 45))})
	@NotNull
	public ViewSubjectWorkId getId() {
		return this.id;
	}

	public void setId(ViewSubjectWorkId id) {
		this.id = id;
	}

}
