package org.srvvp.knowledgetree.entity;
// Generated 5 Apr, 2017 12:15:43 PM by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * WorkInLanguageId generated by hbm2java
 */
@Embeddable
public class WorkInLanguageId implements java.io.Serializable {

	private String work;
	private String language;

	public WorkInLanguageId() {
	}

	public WorkInLanguageId(String work, String language) {
		this.work = work;
		this.language = language;
	}

	@Column(name = "work", nullable = false, length = 20)
	@NotNull
	@Length(max = 20)
	public String getWork() {
		return this.work;
	}

	public void setWork(String work) {
		this.work = work;
	}

	@Column(name = "language", nullable = false, length = 20)
	@NotNull
	@Length(max = 20)
	public String getLanguage() {
		return this.language;
	}

	public void setLanguage(String language) {
		this.language = language;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof WorkInLanguageId))
			return false;
		WorkInLanguageId castOther = (WorkInLanguageId) other;

		return ((this.getWork() == castOther.getWork()) || (this.getWork() != null
				&& castOther.getWork() != null && this.getWork().equals(
				castOther.getWork())))
				&& ((this.getLanguage() == castOther.getLanguage()) || (this
						.getLanguage() != null
						&& castOther.getLanguage() != null && this
						.getLanguage().equals(castOther.getLanguage())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getWork() == null ? 0 : this.getWork().hashCode());
		result = 37 * result
				+ (getLanguage() == null ? 0 : this.getLanguage().hashCode());
		return result;
	}

}
