package org.srvvp.knowledgetree.entity;
// Generated 5 Apr, 2017 12:15:43 PM by Hibernate Tools 3.2.4.GA

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.hibernate.validator.NotNull;

/**
 * WorkHasTag generated by hbm2java
 */
@Entity
@Table(name = "work_has_tag", catalog = "knowledgetree")
public class WorkHasTag implements java.io.Serializable {

	private WorkHasTagId id;
	private Tagwork tagwork;
	private Work work;

	public WorkHasTag() {
	}

	public WorkHasTag(WorkHasTagId id, Tagwork tagwork, Work work) {
		this.id = id;
		this.tagwork = tagwork;
		this.work = work;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "work", column = @Column(name = "work", nullable = false, length = 20)),
			@AttributeOverride(name = "tag", column = @Column(name = "tag", nullable = false))})
	@NotNull
	public WorkHasTagId getId() {
		return this.id;
	}

	public void setId(WorkHasTagId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tag", nullable = false, insertable = false, updatable = false)
	@NotNull
	public Tagwork getTagwork() {
		return this.tagwork;
	}

	public void setTagwork(Tagwork tagwork) {
		this.tagwork = tagwork;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "work", nullable = false, insertable = false, updatable = false)
	@NotNull
	public Work getWork() {
		return this.work;
	}

	public void setWork(Work work) {
		this.work = work;
	}

}
