package org.srvvp.knowledgetree.entity;
// Generated 5 Apr, 2017 12:15:43 PM by Hibernate Tools 3.2.4.GA

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.hibernate.validator.NotNull;

/**
 * WorkInScript generated by hbm2java
 */
@Entity
@Table(name = "work_in_script", catalog = "knowledgetree")
public class WorkInScript implements java.io.Serializable {

	private WorkInScriptId id;
	private Script script;
	private Work work;
	private String location;

	public WorkInScript() {
	}

	public WorkInScript(WorkInScriptId id, Script script, Work work) {
		this.id = id;
		this.script = script;
		this.work = work;
	}
	public WorkInScript(WorkInScriptId id, Script script, Work work,
			String location) {
		this.id = id;
		this.script = script;
		this.work = work;
		this.location = location;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "work", column = @Column(name = "work", nullable = false, length = 20)),
			@AttributeOverride(name = "script", column = @Column(name = "script", nullable = false, length = 20))})
	@NotNull
	public WorkInScriptId getId() {
		return this.id;
	}

	public void setId(WorkInScriptId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "script", nullable = false, insertable = false, updatable = false)
	@NotNull
	public Script getScript() {
		return this.script;
	}

	public void setScript(Script script) {
		this.script = script;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "work", nullable = false, insertable = false, updatable = false)
	@NotNull
	public Work getWork() {
		return this.work;
	}

	public void setWork(Work work) {
		this.work = work;
	}

	@Column(name = "location")
	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

}
