package org.srvvp.knowledgetree.entity;
// Generated 5 Apr, 2017 12:15:43 PM by Hibernate Tools 3.2.4.GA

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.hibernate.validator.NotNull;

/**
 * WorkInLanguage generated by hbm2java
 */
@Entity
@Table(name = "work_in_language", catalog = "knowledgetree")
public class WorkInLanguage implements java.io.Serializable {

	private WorkInLanguageId id;
	private Language language;
	private Work work;
	private String location;

	public WorkInLanguage() {
	}

	public WorkInLanguage(WorkInLanguageId id, Language language, Work work) {
		this.id = id;
		this.language = language;
		this.work = work;
	}
	public WorkInLanguage(WorkInLanguageId id, Language language, Work work,
			String location) {
		this.id = id;
		this.language = language;
		this.work = work;
		this.location = location;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "work", column = @Column(name = "work", nullable = false, length = 20)),
			@AttributeOverride(name = "language", column = @Column(name = "language", nullable = false, length = 20))})
	@NotNull
	public WorkInLanguageId getId() {
		return this.id;
	}

	public void setId(WorkInLanguageId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "language", nullable = false, insertable = false, updatable = false)
	@NotNull
	public Language getLanguage() {
		return this.language;
	}

	public void setLanguage(Language language) {
		this.language = language;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "work", nullable = false, insertable = false, updatable = false)
	@NotNull
	public Work getWork() {
		return this.work;
	}

	public void setWork(Work work) {
		this.work = work;
	}

	@Column(name = "location")
	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

}
