package org.srvvp.knowledgetree.entity;
// Generated 5 Apr, 2017 12:15:43 PM by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * WorkHasTagId generated by hbm2java
 */
@Embeddable
public class WorkHasTagId implements java.io.Serializable {

	private String work;
	private String tag;

	public WorkHasTagId() {
	}

	public WorkHasTagId(String work, String tag) {
		this.work = work;
		this.tag = tag;
	}

	@Column(name = "work", nullable = false, length = 20)
	@NotNull
	@Length(max = 20)
	public String getWork() {
		return this.work;
	}

	public void setWork(String work) {
		this.work = work;
	}

	@Column(name = "tag", nullable = false)
	@NotNull
	public String getTag() {
		return this.tag;
	}

	public void setTag(String tag) {
		this.tag = tag;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof WorkHasTagId))
			return false;
		WorkHasTagId castOther = (WorkHasTagId) other;

		return ((this.getWork() == castOther.getWork()) || (this.getWork() != null
				&& castOther.getWork() != null && this.getWork().equals(
				castOther.getWork())))
				&& ((this.getTag() == castOther.getTag()) || (this.getTag() != null
						&& castOther.getTag() != null && this.getTag().equals(
						castOther.getTag())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getWork() == null ? 0 : this.getWork().hashCode());
		result = 37 * result
				+ (getTag() == null ? 0 : this.getTag().hashCode());
		return result;
	}

}
