package org.srvvp.knowledgetree.entity;
// Generated 5 Apr, 2017 12:15:43 PM by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * WorkInScriptId generated by hbm2java
 */
@Embeddable
public class WorkInScriptId implements java.io.Serializable {

	private String work;
	private String script;

	public WorkInScriptId() {
	}

	public WorkInScriptId(String work, String script) {
		this.work = work;
		this.script = script;
	}

	@Column(name = "work", nullable = false, length = 20)
	@NotNull
	@Length(max = 20)
	public String getWork() {
		return this.work;
	}

	public void setWork(String work) {
		this.work = work;
	}

	@Column(name = "script", nullable = false, length = 20)
	@NotNull
	@Length(max = 20)
	public String getScript() {
		return this.script;
	}

	public void setScript(String script) {
		this.script = script;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof WorkInScriptId))
			return false;
		WorkInScriptId castOther = (WorkInScriptId) other;

		return ((this.getWork() == castOther.getWork()) || (this.getWork() != null
				&& castOther.getWork() != null && this.getWork().equals(
				castOther.getWork())))
				&& ((this.getScript() == castOther.getScript()) || (this
						.getScript() != null
						&& castOther.getScript() != null && this.getScript()
						.equals(castOther.getScript())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getWork() == null ? 0 : this.getWork().hashCode());
		result = 37 * result
				+ (getScript() == null ? 0 : this.getScript().hashCode());
		return result;
	}

}
