package org.srvvp.knowledgetree.entity;
// Generated 3 Oct, 2017 8:09:20 PM by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * District generated by hbm2java
 */
@Entity
@Table(name = "district", catalog = "knowledgetree")
public class District implements java.io.Serializable {

	private DistrictId id;
	private State state;
	private String name;
	private Set<Address> addresses = new HashSet<Address>(0);

	public District() {
	}

	public District(DistrictId id, State state) {
		this.id = id;
		this.state = state;
	}
	public District(DistrictId id, State state, String name,
			Set<Address> addresses) {
		this.id = id;
		this.state = state;
		this.name = name;
		this.addresses = addresses;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "id", column = @Column(name = "id", nullable = false, length = 10)),
			@AttributeOverride(name = "stateId", column = @Column(name = "State_id", nullable = false, length = 10)),
			@AttributeOverride(name = "countryId", column = @Column(name = "Country_id", nullable = false, length = 10))})
	@NotNull
	public DistrictId getId() {
		return this.id;
	}

	public void setId(DistrictId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "State_id", referencedColumnName = "id", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "Country_id", referencedColumnName = "Country_id", nullable = false, insertable = false, updatable = false)})
	@NotNull
	public State getState() {
		return this.state;
	}

	public void setState(State state) {
		this.state = state;
	}

	@Column(name = "Name", length = 30)
	@Length(max = 30)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "district")
	public Set<Address> getAddresses() {
		return this.addresses;
	}

	public void setAddresses(Set<Address> addresses) {
		this.addresses = addresses;
	}

}
