package org.srvvp.knowledgetree.entity;
// Generated 3 Oct, 2017 8:09:20 PM by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Person generated by hbm2java
 */
@Entity
@Table(name = "person", catalog = "knowledgetree")
public class Person implements java.io.Serializable {

	private String id;
	private String first;
	private String middle;
	private String last;
	private String initials;
	private String nick;
	private String other;
	private Set<PersonRelatestoPerson> personRelatestoPersonsForPerson2 = new HashSet<PersonRelatestoPerson>(
			0);
	private Personlife personlife;
	private Set<PersonHasAffiliation> personHasAffiliations = new HashSet<PersonHasAffiliation>(
			0);
	private Set<PersonRelatestoPerson> personRelatestoPersonsForPerson1 = new HashSet<PersonRelatestoPerson>(
			0);
	private Set<PersonHasWork> personHasWorks = new HashSet<PersonHasWork>(0);
	private Set<PersonHasRole> personHasRoles = new HashSet<PersonHasRole>(0);
	private Set<Address> addresses = new HashSet<Address>(0);

	public Person() {
	}

	public Person(String id) {
		this.id = id;
	}
	public Person(String id, String first, String middle, String last,
			String initials, String nick, String other,
			Set<PersonRelatestoPerson> personRelatestoPersonsForPerson2,
			Personlife personlife,
			Set<PersonHasAffiliation> personHasAffiliations,
			Set<PersonRelatestoPerson> personRelatestoPersonsForPerson1,
			Set<PersonHasWork> personHasWorks,
			Set<PersonHasRole> personHasRoles, Set<Address> addresses) {
		this.id = id;
		this.first = first;
		this.middle = middle;
		this.last = last;
		this.initials = initials;
		this.nick = nick;
		this.other = other;
		this.personRelatestoPersonsForPerson2 = personRelatestoPersonsForPerson2;
		this.personlife = personlife;
		this.personHasAffiliations = personHasAffiliations;
		this.personRelatestoPersonsForPerson1 = personRelatestoPersonsForPerson1;
		this.personHasWorks = personHasWorks;
		this.personHasRoles = personHasRoles;
		this.addresses = addresses;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, length = 20)
	@NotNull
	@Length(max = 20)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "First", length = 30)
	@Length(max = 30)
	public String getFirst() {
		return this.first;
	}

	public void setFirst(String first) {
		this.first = first;
	}

	@Column(name = "Middle", length = 30)
	@Length(max = 30)
	public String getMiddle() {
		return this.middle;
	}

	public void setMiddle(String middle) {
		this.middle = middle;
	}

	@Column(name = "Last", length = 30)
	@Length(max = 30)
	public String getLast() {
		return this.last;
	}

	public void setLast(String last) {
		this.last = last;
	}

	@Column(name = "Initials", length = 10)
	@Length(max = 10)
	public String getInitials() {
		return this.initials;
	}

	public void setInitials(String initials) {
		this.initials = initials;
	}

	@Column(name = "Nick", length = 20)
	@Length(max = 20)
	public String getNick() {
		return this.nick;
	}

	public void setNick(String nick) {
		this.nick = nick;
	}

	@Column(name = "Other", length = 30)
	@Length(max = 30)
	public String getOther() {
		return this.other;
	}

	public void setOther(String other) {
		this.other = other;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "personByPerson2")
	public Set<PersonRelatestoPerson> getPersonRelatestoPersonsForPerson2() {
		return this.personRelatestoPersonsForPerson2;
	}

	public void setPersonRelatestoPersonsForPerson2(
			Set<PersonRelatestoPerson> personRelatestoPersonsForPerson2) {
		this.personRelatestoPersonsForPerson2 = personRelatestoPersonsForPerson2;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "person")
	@Length(max = 10)
	public Personlife getPersonlife() {
		return this.personlife;
	}

	public void setPersonlife(Personlife personlife) {
		this.personlife = personlife;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "person")
	public Set<PersonHasAffiliation> getPersonHasAffiliations() {
		return this.personHasAffiliations;
	}

	public void setPersonHasAffiliations(
			Set<PersonHasAffiliation> personHasAffiliations) {
		this.personHasAffiliations = personHasAffiliations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "personByPerson1")
	public Set<PersonRelatestoPerson> getPersonRelatestoPersonsForPerson1() {
		return this.personRelatestoPersonsForPerson1;
	}

	public void setPersonRelatestoPersonsForPerson1(
			Set<PersonRelatestoPerson> personRelatestoPersonsForPerson1) {
		this.personRelatestoPersonsForPerson1 = personRelatestoPersonsForPerson1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "person")
	public Set<PersonHasWork> getPersonHasWorks() {
		return this.personHasWorks;
	}

	public void setPersonHasWorks(Set<PersonHasWork> personHasWorks) {
		this.personHasWorks = personHasWorks;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "person")
	public Set<PersonHasRole> getPersonHasRoles() {
		return this.personHasRoles;
	}

	public void setPersonHasRoles(Set<PersonHasRole> personHasRoles) {
		this.personHasRoles = personHasRoles;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "person")
	public Set<Address> getAddresses() {
		return this.addresses;
	}

	public void setAddresses(Set<Address> addresses) {
		this.addresses = addresses;
	}

}
