package org.srvvp.knowledgetree.entity;
// Generated 3 Oct, 2017 8:09:20 PM by Hibernate Tools 3.2.4.GA

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.hibernate.validator.NotNull;

/**
 * PersonHasRole generated by hbm2java
 */
@Entity
@Table(name = "person_has_role", catalog = "knowledgetree")
public class PersonHasRole implements java.io.Serializable {

	private PersonHasRoleId id;
	private Role role;
	private Person person;

	public PersonHasRole() {
	}

	public PersonHasRole(PersonHasRoleId id, Role role, Person person) {
		this.id = id;
		this.role = role;
		this.person = person;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "person", column = @Column(name = "person", nullable = false, length = 20)),
			@AttributeOverride(name = "role", column = @Column(name = "role", nullable = false, length = 20))})
	@NotNull
	public PersonHasRoleId getId() {
		return this.id;
	}

	public void setId(PersonHasRoleId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "role", nullable = false, insertable = false, updatable = false)
	@NotNull
	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "person", nullable = false, insertable = false, updatable = false)
	@NotNull
	public Person getPerson() {
		return this.person;
	}

	public void setPerson(Person person) {
		this.person = person;
	}

}
