package org.srvvp.knowledgetree.entity;
// Generated 3 Oct, 2017 8:09:20 PM by Hibernate Tools 3.2.4.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Personlife generated by hbm2java
 */
@Entity
@Table(name = "personlife", catalog = "knowledgetree")
public class Personlife implements java.io.Serializable {

	private String id;
	private Person person;
	private Boolean living;
	private Date birth;
	private Date death;
	private String period;
	private String history;
	private String life;

	public Personlife() {
	}

	public Personlife(Person person) {
		this.person = person;
	}
	public Personlife(Person person, Boolean living, Date birth, Date death,
			String period, String history, String life) {
		this.person = person;
		this.living = living;
		this.birth = birth;
		this.death = death;
		this.period = period;
		this.history = history;
		this.life = life;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "person"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "id", unique = true, nullable = false, length = 10)
	@Length(max = 10)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	@NotNull
	@Length(max = 10)
	public Person getPerson() {
		return this.person;
	}

	public void setPerson(Person person) {
		this.person = person;
	}

	@Column(name = "Living")
	public Boolean getLiving() {
		return this.living;
	}

	public void setLiving(Boolean living) {
		this.living = living;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Birth", length = 10)
	public Date getBirth() {
		return this.birth;
	}

	public void setBirth(Date birth) {
		this.birth = birth;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Death", length = 10)
	public Date getDeath() {
		return this.death;
	}

	public void setDeath(Date death) {
		this.death = death;
	}

	@Column(name = "Period", length = 25)
	@Length(max = 25)
	public String getPeriod() {
		return this.period;
	}

	public void setPeriod(String period) {
		this.period = period;
	}

	@Column(name = "History")
	public String getHistory() {
		return this.history;
	}

	public void setHistory(String history) {
		this.history = history;
	}

	@Column(name = "Life")
	public String getLife() {
		return this.life;
	}

	public void setLife(String life) {
		this.life = life;
	}

}
