package org.srvvp.knowledgetree.entity;
// Generated 3 Oct, 2017 8:09:20 PM by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * PersonRelatestoPersonId generated by hbm2java
 */
@Embeddable
public class PersonRelatestoPersonId implements java.io.Serializable {

	private String person1;
	private String person2;
	private String relation;

	public PersonRelatestoPersonId() {
	}

	public PersonRelatestoPersonId(String person1, String person2,
			String relation) {
		this.person1 = person1;
		this.person2 = person2;
		this.relation = relation;
	}

	@Column(name = "person1", nullable = false, length = 20)
	@NotNull
	@Length(max = 20)
	public String getPerson1() {
		return this.person1;
	}

	public void setPerson1(String person1) {
		this.person1 = person1;
	}

	@Column(name = "person2", nullable = false, length = 20)
	@NotNull
	@Length(max = 20)
	public String getPerson2() {
		return this.person2;
	}

	public void setPerson2(String person2) {
		this.person2 = person2;
	}

	@Column(name = "relation", nullable = false, length = 20)
	@NotNull
	@Length(max = 20)
	public String getRelation() {
		return this.relation;
	}

	public void setRelation(String relation) {
		this.relation = relation;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PersonRelatestoPersonId))
			return false;
		PersonRelatestoPersonId castOther = (PersonRelatestoPersonId) other;

		return ((this.getPerson1() == castOther.getPerson1()) || (this
				.getPerson1() != null
				&& castOther.getPerson1() != null && this.getPerson1().equals(
				castOther.getPerson1())))
				&& ((this.getPerson2() == castOther.getPerson2()) || (this
						.getPerson2() != null
						&& castOther.getPerson2() != null && this.getPerson2()
						.equals(castOther.getPerson2())))
				&& ((this.getRelation() == castOther.getRelation()) || (this
						.getRelation() != null
						&& castOther.getRelation() != null && this
						.getRelation().equals(castOther.getRelation())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getPerson1() == null ? 0 : this.getPerson1().hashCode());
		result = 37 * result
				+ (getPerson2() == null ? 0 : this.getPerson2().hashCode());
		result = 37 * result
				+ (getRelation() == null ? 0 : this.getRelation().hashCode());
		return result;
	}

}
