package org.srvvp.knowledgetree.entity;
// Generated 3 Oct, 2017 8:09:20 PM by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * PersonPersonRelation generated by hbm2java
 */
@Entity
@Table(name = "person_person_relation", catalog = "knowledgetree")
public class PersonPersonRelation implements java.io.Serializable {

	private String id;
	private String name;
	private String description;
	private Set<PersonRelatestoPerson> personRelatestoPersons = new HashSet<PersonRelatestoPerson>(
			0);

	public PersonPersonRelation() {
	}

	public PersonPersonRelation(String id) {
		this.id = id;
	}
	public PersonPersonRelation(String id, String name, String description,
			Set<PersonRelatestoPerson> personRelatestoPersons) {
		this.id = id;
		this.name = name;
		this.description = description;
		this.personRelatestoPersons = personRelatestoPersons;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, length = 20)
	@NotNull
	@Length(max = 20)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "Name", length = 100)
	@Length(max = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "Description", length = 1000)
	@Length(max = 1000)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "personPersonRelation")
	public Set<PersonRelatestoPerson> getPersonRelatestoPersons() {
		return this.personRelatestoPersons;
	}

	public void setPersonRelatestoPersons(
			Set<PersonRelatestoPerson> personRelatestoPersons) {
		this.personRelatestoPersons = personRelatestoPersons;
	}

}
