package org.srvvp.knowledgetree.entity;
// Generated 3 Oct, 2017 8:09:20 PM by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * PersonHasAffiliationId generated by hbm2java
 */
@Embeddable
public class PersonHasAffiliationId implements java.io.Serializable {

	private String person;
	private String affiliation;

	public PersonHasAffiliationId() {
	}

	public PersonHasAffiliationId(String person, String affiliation) {
		this.person = person;
		this.affiliation = affiliation;
	}

	@Column(name = "person", nullable = false, length = 20)
	@NotNull
	@Length(max = 20)
	public String getPerson() {
		return this.person;
	}

	public void setPerson(String person) {
		this.person = person;
	}

	@Column(name = "affiliation", nullable = false, length = 20)
	@NotNull
	@Length(max = 20)
	public String getAffiliation() {
		return this.affiliation;
	}

	public void setAffiliation(String affiliation) {
		this.affiliation = affiliation;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PersonHasAffiliationId))
			return false;
		PersonHasAffiliationId castOther = (PersonHasAffiliationId) other;

		return ((this.getPerson() == castOther.getPerson()) || (this
				.getPerson() != null
				&& castOther.getPerson() != null && this.getPerson().equals(
				castOther.getPerson())))
				&& ((this.getAffiliation() == castOther.getAffiliation()) || (this
						.getAffiliation() != null
						&& castOther.getAffiliation() != null && this
						.getAffiliation().equals(castOther.getAffiliation())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getPerson() == null ? 0 : this.getPerson().hashCode());
		result = 37
				* result
				+ (getAffiliation() == null ? 0 : this.getAffiliation()
						.hashCode());
		return result;
	}

}
