package org.srvvp.knowledgetree.entity;
// Generated 3 Oct, 2017 8:09:20 PM by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * PersonHasWorkId generated by hbm2java
 */
@Embeddable
public class PersonHasWorkId implements java.io.Serializable {

	private String person;
	private String work;
	private String relation;

	public PersonHasWorkId() {
	}

	public PersonHasWorkId(String person, String work, String relation) {
		this.person = person;
		this.work = work;
		this.relation = relation;
	}

	@Column(name = "Person", nullable = false, length = 20)
	@NotNull
	@Length(max = 20)
	public String getPerson() {
		return this.person;
	}

	public void setPerson(String person) {
		this.person = person;
	}

	@Column(name = "Work", nullable = false, length = 20)
	@NotNull
	@Length(max = 20)
	public String getWork() {
		return this.work;
	}

	public void setWork(String work) {
		this.work = work;
	}

	@Column(name = "Relation", nullable = false, length = 20)
	@NotNull
	@Length(max = 20)
	public String getRelation() {
		return this.relation;
	}

	public void setRelation(String relation) {
		this.relation = relation;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PersonHasWorkId))
			return false;
		PersonHasWorkId castOther = (PersonHasWorkId) other;

		return ((this.getPerson() == castOther.getPerson()) || (this
				.getPerson() != null
				&& castOther.getPerson() != null && this.getPerson().equals(
				castOther.getPerson())))
				&& ((this.getWork() == castOther.getWork()) || (this.getWork() != null
						&& castOther.getWork() != null && this.getWork()
						.equals(castOther.getWork())))
				&& ((this.getRelation() == castOther.getRelation()) || (this
						.getRelation() != null
						&& castOther.getRelation() != null && this
						.getRelation().equals(castOther.getRelation())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getPerson() == null ? 0 : this.getPerson().hashCode());
		result = 37 * result
				+ (getWork() == null ? 0 : this.getWork().hashCode());
		result = 37 * result
				+ (getRelation() == null ? 0 : this.getRelation().hashCode());
		return result;
	}

}
