package org.srvvp.knowledgetree.entity;
// Generated 3 Oct, 2017 8:09:20 PM by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * PersonWorkRelation generated by hbm2java
 */
@Entity
@Table(name = "person_work_relation", catalog = "knowledgetree")
public class PersonWorkRelation implements java.io.Serializable {

	private String id;
	private String name;
	private String description;
	private Set<PersonHasWork> personHasWorks = new HashSet<PersonHasWork>(0);

	public PersonWorkRelation() {
	}

	public PersonWorkRelation(String id) {
		this.id = id;
	}
	public PersonWorkRelation(String id, String name, String description,
			Set<PersonHasWork> personHasWorks) {
		this.id = id;
		this.name = name;
		this.description = description;
		this.personHasWorks = personHasWorks;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, length = 20)
	@NotNull
	@Length(max = 20)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "Name", length = 45)
	@Length(max = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "Description", length = 1000)
	@Length(max = 1000)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "personWorkRelation")
	public Set<PersonHasWork> getPersonHasWorks() {
		return this.personHasWorks;
	}

	public void setPersonHasWorks(Set<PersonHasWork> personHasWorks) {
		this.personHasWorks = personHasWorks;
	}

}
