package org.srvvp.knowledgetree.entity;
// Generated 3 Oct, 2017 8:09:20 PM by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Script generated by hbm2java
 */
@Entity
@Table(name = "script", catalog = "knowledgetree")
public class Script implements java.io.Serializable {

	private String id;
	private String name;
	private Set<WorkInScript> workInScripts = new HashSet<WorkInScript>(0);

	public Script() {
	}

	public Script(String id) {
		this.id = id;
	}
	public Script(String id, String name, Set<WorkInScript> workInScripts) {
		this.id = id;
		this.name = name;
		this.workInScripts = workInScripts;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, length = 20)
	@NotNull
	@Length(max = 20)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "Name", length = 100)
	@Length(max = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "script")
	public Set<WorkInScript> getWorkInScripts() {
		return this.workInScripts;
	}

	public void setWorkInScripts(Set<WorkInScript> workInScripts) {
		this.workInScripts = workInScripts;
	}

}
