package org.srvvp.knowledgetree.entity;
// Generated 3 Oct, 2017 8:09:20 PM by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * SubjectHasWorkId generated by hbm2java
 */
@Embeddable
public class SubjectHasWorkId implements java.io.Serializable {

	private String subject;
	private String work;
	private String relation;

	public SubjectHasWorkId() {
	}

	public SubjectHasWorkId(String subject, String work, String relation) {
		this.subject = subject;
		this.work = work;
		this.relation = relation;
	}

	@Column(name = "Subject", nullable = false, length = 20)
	@NotNull
	@Length(max = 20)
	public String getSubject() {
		return this.subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

	@Column(name = "Work", nullable = false, length = 20)
	@NotNull
	@Length(max = 20)
	public String getWork() {
		return this.work;
	}

	public void setWork(String work) {
		this.work = work;
	}

	@Column(name = "Relation", nullable = false, length = 20)
	@NotNull
	@Length(max = 20)
	public String getRelation() {
		return this.relation;
	}

	public void setRelation(String relation) {
		this.relation = relation;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SubjectHasWorkId))
			return false;
		SubjectHasWorkId castOther = (SubjectHasWorkId) other;

		return ((this.getSubject() == castOther.getSubject()) || (this
				.getSubject() != null
				&& castOther.getSubject() != null && this.getSubject().equals(
				castOther.getSubject())))
				&& ((this.getWork() == castOther.getWork()) || (this.getWork() != null
						&& castOther.getWork() != null && this.getWork()
						.equals(castOther.getWork())))
				&& ((this.getRelation() == castOther.getRelation()) || (this
						.getRelation() != null
						&& castOther.getRelation() != null && this
						.getRelation().equals(castOther.getRelation())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getSubject() == null ? 0 : this.getSubject().hashCode());
		result = 37 * result
				+ (getWork() == null ? 0 : this.getWork().hashCode());
		result = 37 * result
				+ (getRelation() == null ? 0 : this.getRelation().hashCode());
		return result;
	}

}
