package org.srvvp.knowledgetree.entity;
// Generated 3 Oct, 2017 8:09:20 PM by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * SubjectRelatestoSubjectId generated by hbm2java
 */
@Embeddable
public class SubjectRelatestoSubjectId implements java.io.Serializable {

	private String subject1;
	private String subject2;

	public SubjectRelatestoSubjectId() {
	}

	public SubjectRelatestoSubjectId(String subject1, String subject2) {
		this.subject1 = subject1;
		this.subject2 = subject2;
	}

	@Column(name = "Subject1", nullable = false, length = 20)
	@NotNull
	@Length(max = 20)
	public String getSubject1() {
		return this.subject1;
	}

	public void setSubject1(String subject1) {
		this.subject1 = subject1;
	}

	@Column(name = "Subject2", nullable = false, length = 20)
	@NotNull
	@Length(max = 20)
	public String getSubject2() {
		return this.subject2;
	}

	public void setSubject2(String subject2) {
		this.subject2 = subject2;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SubjectRelatestoSubjectId))
			return false;
		SubjectRelatestoSubjectId castOther = (SubjectRelatestoSubjectId) other;

		return ((this.getSubject1() == castOther.getSubject1()) || (this
				.getSubject1() != null
				&& castOther.getSubject1() != null && this.getSubject1()
				.equals(castOther.getSubject1())))
				&& ((this.getSubject2() == castOther.getSubject2()) || (this
						.getSubject2() != null
						&& castOther.getSubject2() != null && this
						.getSubject2().equals(castOther.getSubject2())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getSubject1() == null ? 0 : this.getSubject1().hashCode());
		result = 37 * result
				+ (getSubject2() == null ? 0 : this.getSubject2().hashCode());
		return result;
	}

}
