package org.srvvp.knowledgetree.entity;
// Generated 3 Oct, 2017 8:09:20 PM by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * WorkRelatestoWorkId generated by hbm2java
 */
@Embeddable
public class WorkRelatestoWorkId implements java.io.Serializable {

	private String work1;
	private String work2;

	public WorkRelatestoWorkId() {
	}

	public WorkRelatestoWorkId(String work1, String work2) {
		this.work1 = work1;
		this.work2 = work2;
	}

	@Column(name = "Work1", nullable = false, length = 20)
	@NotNull
	@Length(max = 20)
	public String getWork1() {
		return this.work1;
	}

	public void setWork1(String work1) {
		this.work1 = work1;
	}

	@Column(name = "Work2", nullable = false, length = 20)
	@NotNull
	@Length(max = 20)
	public String getWork2() {
		return this.work2;
	}

	public void setWork2(String work2) {
		this.work2 = work2;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof WorkRelatestoWorkId))
			return false;
		WorkRelatestoWorkId castOther = (WorkRelatestoWorkId) other;

		return ((this.getWork1() == castOther.getWork1()) || (this.getWork1() != null
				&& castOther.getWork1() != null && this.getWork1().equals(
				castOther.getWork1())))
				&& ((this.getWork2() == castOther.getWork2()) || (this
						.getWork2() != null
						&& castOther.getWork2() != null && this.getWork2()
						.equals(castOther.getWork2())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getWork1() == null ? 0 : this.getWork1().hashCode());
		result = 37 * result
				+ (getWork2() == null ? 0 : this.getWork2().hashCode());
		return result;
	}

}
